### ISSUE TITLE
[Bug Report] Mage Arcane Missiles spell does not proc any trinkets/items

### ISSUE THREAD

**Issue by cosminpandelache** [BlessedCammi/TBC5MAN-Bug-Tracker#109]
@Yatzii93 **EDIT**: 1.9 patch from Vaniilia: https://wowwiki.fandom.com/wiki/Patch_1.9.0 (Arcane Missiles - Will now be able to trigger procs based on dealing damage)

2.2.0 from TBC: https://wowwiki.fandom.com/wiki/Patch_2.2.0 (Arcane Missiles: Some procs were not triggered by this spell and now will be (such as Eye of Magtheridon)

Bug fix on 
 
Proof: Fom retail : https://youtu.be/c2RtyFh5TnE?t=19

You can see both Eye of Quagmiran and The Lighting Capactior procs when using Arcane Missiles. Also you can see the clearcasting proc on the first hit of the spell.

Mage Arcane Missles spell does not proc any trinkets/items. Eye of Quagmiran (the one that procs and increases your haste rating) or the ring from reputation with Hijal (that has a chance on hit to increase spell dmg) equipped, don't proc when using arcane missles.

I just got The Lightning Capacitor Trinket (the trinket from Karazahan) - It does not proc as well when using Arcane Missiles. Also the trinket does not Crit (I will open another issue with this, 23 hits on the trinket - 0 Crits with 35% crit chance) - easy to replicate as well.

My guess is this spell does not proc any on-hit effects/procs. 

To test/replicate this, create a mage, equippe any items that have a chance to proc on spell hit and then use Aracane Missles spell on a target dummy. Items will not proc. ( also tested it on different mobs, and bosses -> same result, no procs)

See screenshot with my hits and 0 procs on both items that I had equipped and did not porc once. (eye of quagmiran and the rep ring from Hijal)
![WoWScrnShot_092820_192408](https://user-images.githubusercontent.com/51449123/94616455-aa9fd300-02b1-11eb-991a-91e95e5baa2b.jpg)

**Comment by Yatzii93** [comment]
Any proof it should?

**Comment by cosminpandelache** [comment]
Hello, here is a clip where you can see the The lighting capacitor procing every time arcane missles crit: https://youtu.be/cD75fx_kce4?t=388

Also here, from retail I think this is: https://youtu.be/c2RtyFh5TnE?t=19

Let me know if you need any other tests or additional info.

**Comment by cosminpandelache** [comment]
As for the lighting capactior that should crit: https://wow.gamepedia.com/The_Lightning_Capacitor, https://wowwiki.fandom.com/wiki/The_Lightning_Capacitor. Search for "Crit" to be easier to find, both posts mention the crit chance on this trinket. If you wish to open another thread for this one I'll be more than happy.

Let me know again if you need anything else Yatzi!

**Comment by cosminpandelache** [comment]
Hei again Yatzi, if you need a recording with my mage doing dps on a dummy for several minutes to show that the trinket does not crit and the Aracane Missles do not proc any items pleaset let me know. I can do that as well if it helps with the testing.

**Comment by m17a4y** [comment]
I agree with @cosminpandelache on all of his reports about Arcane Missiles and [The Lightning Capacitor], I also found out that the T6 bonus doesn't work for Arcane Missiles, in fact, it is doing more damage without 4 pieces of T6 and less damage with 4 pieces equipped. I hope you see the update where @cosminpandelache added more proof

**Comment by Yatzii93** [comment]
I'll have a look at this tomorrow and update accordingly.

**Comment by Yatzii93** [comment]
I've made some progress but have run into another issue blocking the fix. Trying to unravel it but ye it's quite particuliar and may take some time to fix considering there's alot of moving parts.

**Comment by cosminpandelache** [comment]
Thanks for the update @Yatzii93. I know you are very busy and we reallly appreciate your effort. Can wait to try the Arcane Missles build when you'll be done :D Take care and thank you again, you did a really great job with this server!

**Comment by m17a4y** [comment]
Thanks for the update!
