### ISSUE TITLE
🐛 [Bug Report] - Bloodthirst not benefiting from attack power vs demons

### ISSUE THREAD

**Issue by brokenthingsareannoying** [BlessedCammi/TBC5MAN-Bug-Tracker#122]
# Decription: #
Bloodthirst is not benefiting from attack power against demons like glaives 2 set bonus or elixir of demonslaying etc.
# How it works: #
Attack power against specific creature types is not applying to bloodthirst
# How it should work: #
Attack power against specific creature types should apply to bloodthirst
# Source - You need to provide a source as evidence: #
https://wow.gamepedia.com/Bloodthirst
Patch 1.12.0 (2006-08-22): This ability will now correctly benefit from attack power bonuses versus specific creature types. 
# Additional Information: #
Another thing not applying to Bloodthirst is the Improved Hunter's Mark melee attack power.

**Comment by Yatzii93** [comment]
I will check this, the codes there to check on spell damage if the source is a melee attack.

**Comment by Yatzii93** [comment]
Ive looked at it and to fix this requires quite a big rewrite. Fixing it will break some other spells unfortunately. When I get more time I can try and tackle it. It wasn't coded well to begin with, but granted it's complex so it's easy to see how this happened. There's a lot of moving parts. A lot of spells run through the same code for efficiency, the code needs to work for everything. Unfortunately this is 1 example where the code fails to accommodate one specific thing for 1 spell.
but right now this 1 bug is better than having other class stuff break, much more costly breaks too.

**Comment by valens14** [comment]
![Untitled](https://user-images.githubusercontent.com/6764108/224469645-9f2a9287-3894-4ae0-948e-b0712e0782b1.png)

This should fix it. The top portion is the section of code that is currently in the cmangos core for bloodthirst damage calculation in SpellEffects.cpp. Changing it to the bottom portion should fix this bug.
