### ISSUE TITLE
🐛 [Bug Report] - PvP DR ( Diminishing returns ) too short

### ISSUE THREAD

**Issue by Tankdiehutte** [BlessedCammi/TBC5MAN-Bug-Tracker#171]
# Decription: #
The DRs on cc spells are to short, allowing cc comps to easily build an endless cc chain.
# How it works: #
If a Player gets cced every following cc of the same DR within 15s after the effect ends ( running out / break by damage/ PvP trinket) gets half duration. This means that a player can e.g. cast 3x cyclone (6s+3s+1.5s), then 3x roots with 1s overlap ( 10s+5s+2.5s -2x1s = 15.5s) and then 3x cyclone again. If he has an arenamate with cc not sharing this DR he can basicly build a cc chain that only breaks if they fail.
# How it should work: #
The DR window should be randomly 15-20s to give options for counterplay and avoid 2v1 situations.
# Source - You need to provide a source as evidence: #
https://wowwiki-archive.fandom.com/wiki/Diminishing_returns
https://www.youtube.com/watch?v=nS8xWIl3ntM
[![image](https://user-images.githubusercontent.com/56139988/233818099-809ca1ca-e92a-4e05-8f5a-76a26fe2474b.png)
](https://wowwiki-archive.fandom.com/wiki/Diminishing_returns#:~:text=As%20a%20result%2C%20a%20particular,after%2018%20seconds%20by%20default.)
# Additional Information: #
- Crawl even said that it should be 20s
- If you look in the comments of the source the creator even admits that mistake in the comments. And you see its >=18 in his practical test.
- Currently its close to impossible to play arena againts rogue/mage comps if you are not a rogue/mage since its close to impossible to break free.

**Comment by Yatzii93** [comment]
No proof from official sources. 15 seconds seems to be valid, unless proven otherwise.

**Comment by Tankdiehutte** [comment]
The 15s-20s Diminishing Return reset window got changed with a Hotfix on Patch 6.1 
https://worldofwarcraft.blizzard.com/en-gb/news/18061645/61-hotfixes-march-23
![image](https://github.com/Yatzii93/TBC5MAN-Bug-Tracker/assets/56139988/6c0a4d39-d69a-4411-b715-b682d56ade81)

**Comment by Tankdiehutte** [comment]
https://www.icy-veins.com/forums/topic/11168-patch-61-crowd-control-diminishing-return-hotfix/
Screenshot of the original Post. (Sadly the forumpage is no longer available on blizzards forum).

**Comment by Tankdiehutte** [comment]
https://www.reddit.com/r/worldofpvp/comments/10g0z4d/diminishing_returns_duration/
![image](https://github.com/Yatzii93/TBC5MAN-Bug-Tracker/assets/56139988/609833be-ca79-4607-961b-431db77fe374)

**Comment by Tankdiehutte** [comment]
https://silentshadows.net/tbc-diminishing-returns-list/
Another source showing blizzard using the old system for classic: Dynamic 15s-20s instead of fixed 18s.
![image](https://github.com/Yatzii93/TBC5MAN-Bug-Tracker/assets/56139988/70996b4c-1bf3-405b-9b74-bd3418bf3966)
