### ISSUE TITLE
🐛 [High King Maulgar] - Kiggler the Crazed doesnt cast spells on (some) pets

### ISSUE THREAD

**Issue by Tankdiehutte** [BlessedCammi/TBC5MAN-Bug-Tracker#180]
# Decription: #
Kiggler the Crazed doesnt cast his Lightning Bolt on (some) pets.
# How it works: #
Currently a frequently used Bug is letting Hunter & Warlock pets tank Kiggler The Crazed due to Voidwalkers being demons ( not sheepable ) and sheeped Hunterpets not being a big issue.
# How it should work: #
Kiggler The Crazed should atleast cast Lightning bolt on the pets forcing the healer to heal the pet.
# Source - You need to provide a source as evidence: #
The Mob just does nothing ( not even autohits ) when targetting a Void walker. While i dont see any Guide mentioning that a hostile mob actually attacks, i also dont see a guide saying it does nothing.
https://www.wowhead.com/tbc/npc=18835/kiggler-the-crazed
# Additional Information: #
- Kiggöer the Crazed has brutally high autohit damage, quickly turning the fight into a wipe if the mob gets kicked. Maybe the Autohit damage should be reduced too in case the mob suddenly starts attacking people.
- This bug turned into an actual pug strategy due to eliminating the only real danger in that fight ( Tank or heal getting sheeped by Kiggler). So telling people after the fix could lead to less frustration.
- I'm not sure if its just the Voidwalker and just some hunterpets. ( I can just report what i saw being done )

**Comment by BlessedCammi** [comment]
Fixed on next restart.
