### ISSUE TITLE
🐛 [Leotheras the Blind / SSC] - Demonform does no Damage to Pets making cheesy strats possible.

### ISSUE THREAD

**Issue by Tankdiehutte** [BlessedCammi/TBC5MAN-Bug-Tracker#181]
# Decription: #
Leotheras the Blinds Demonform / Demon in last phase. Does not damage pets.
# How it works: #
Hunterpets, Warlockpets & Elementaltotems are used in the last Phase to soak the Spell casted by the demon, since the spell doesnt do damage to them.
# How it should work: #
The Spell should hit Players applying a stacking debuff, forcing the players to kill the boss quickly before the demon does too much damage.
# Source - You need to provide a source as evidence: #
- Its a TBC5Man QOL change, that is abused to cheese the boss / making it a complete joke.
Boss: https://www.wowhead.com/tbc/npc=21215/leotheras-the-blind#abilities;mode:n25
15% Split Boss: https://www.wowhead.com/tbc/npc=21875/shadow-of-leotheras
Ability: https://www.wowhead.com/tbc/spell=37675/chaos-blast
# Additional Information: #
- The Spell could be made completely singletarget or given only a much smaller radius to avoid pets running in range of that spell.
- While i havent seen people doing it, its possible to just let pets tank the boss in the demonphase before 15% to let the healer regenerate his Mana. ( However most people can't count 1 and 1 together and will just tank the demon, die to 15 stacks and flame the healer xD)

**Comment by BlessedCammi** [comment]
Fixed in next restart.
