### ISSUE TITLE
🐛 [Illidan] - Boss can cast Draw Soul onto a target that doesnt have Aggro

### ISSUE THREAD

**Issue by Tankdiehutte** [BlessedCammi/TBC5MAN-Bug-Tracker#214]
# Decription: #
Boss can cast Draw Soul onto a target that doesnt have Aggro.
# How it works: #
When Illidan casts Draw Soul right when he puts the parasite debuff on someone, he can cast Draw soul on the same Person, who is stacked with the rest of the group ( -> 7k Damage on the whole grp on CM ).
# How it should work: #
The boss should target the person that has aggro first, before casting Draw soul.
# Source - You need to provide a source as evidence: #
https://www.wowhead.com/tbc/spell=40904/draw-soul
# Additional Information: #
- Just putting Draw soul on a 1s cooldown or resetting the Parasite cooldown to 0s on every phasechance would fix the bug.

**Comment by BlessedCammi** [comment]
Boss should no longer turn when casting 'Parasitic Shadowfiend', needs a restart.
