### ISSUE TITLE
🐛 [Item] - Mystical Skyfire Diamond ( Best in slot shadowpriest meta gem til Sunwell )

### ISSUE THREAD

**Issue by Tankdiehutte** [BlessedCammi/TBC5MAN-Bug-Tracker#218]
# Decription: #
Buffduration too short
# How it works: #
Buff lasts 4s.
# How it should work: #
Buff should last 6s.
# Source - You need to provide a source as evidence: #
- https://www.wowhead.com/tbc/spell=32837/spell-focus-trigger
# Additional Information: #
Video showing the Bug:
https://www.youtube.com/watch?v=kxf1SkYSwck

**Comment by BlessedCammi** [comment]
![image](https://github.com/user-attachments/assets/c5aae83d-e250-4d76-bab8-f688bb455e6a)

uses this spell which is only 4 seconds duration. The tooltip isn't shown on the item in game, so I suspect it's meant to only be 4 seconds considering the spell it uses is set at a 4 second duration.

**Comment by Tankdiehutte** [comment]
https://wowwiki-archive.fandom.com/wiki/Mystical_Skyfire_Diamond

![image](https://github.com/user-attachments/assets/bd9e2a47-3a1f-4a3f-9604-0534b0ebbe46)

**Comment by Tankdiehutte** [comment]
Can be closed then
